server:
  port: 8889

eureka:
  instance:
    hostname: localhost


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: playerAuction-service
          uri: lb://playerAuction-service
          predicates:
            - Path=/team/**,/player/**
            
            
        